### ISSUE TITLE
integrate linting and code quality tools

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood-getting-started#26]
To help keep things consistent when contributing to this project, we should probably integrate the same tools we are using in Greenwood
- **ESLint**
- **Stylelint**
- **Ls-lint**

We should mimic Greenwood and create a grouped [`lint` npm script](https://github.com/ProjectEvergreen/greenwood/blob/master/package.json#L26) and make sure that gets added to our [GitHub Actions here](https://github.com/ProjectEvergreen/greenwood-getting-started/tree/master/.github/workflows).

**Comment by aholtzman** [comment]
I agree that we should add the scripts in to the package.json file and all the setup, but the GitHub Actions part I think should be optional for the end user. Having it there to be used if chosen to do so is good, but I do not think we should kind of mandate it. 

Perhaps just leaving instructions on how to implement it in the CI process if they choose to would be a good compromise?

**Comment by thescientist13** [comment]
I guess if we add it, but then aren't putting into GitHub Actions / automate it, then wouldn't we lose the value of adding it in the first place, from the POV of maintaining this project (from a code quality perspective)?

If you mean from the perspective of a user of Greenwood, our [Getting Started]() doesn't cover CI or anything like that and basically just focuses on the contents of the _src/_ directory for the most part, so I think in that way the overhead is low?

Maybe some additional text in the README to let the user know how the repo is maintained is optional from the contents / demonstrable value inside it?  e.g. _"refer to our guide, follow that, everything else you see is optional, etc_"

Thoughts?

**Comment by aholtzman** [comment]
Just thinking that someone using this as a starting point may not want to have the same standards we use imposed upon them. Having the tooling in place so they can use it (and adapt it) makes sense - they can chose to run `yarn lint` but not have GH get grumpy with them if a `;` is missing (if that is how they want to roll). I like the idea of developer choice/freedom with making it an easy nudge into using some good practices.

That said, I will happily put it in if you prefer.

**Comment by thescientist13** [comment]
Ah, so you're thinking that if they fork, then they'll pull our GitHub Action's config along with it, linting and all?

If so, could the message also act as that way to emphasize communicate that as well?  I mean either way, they can delete / change whatever they want, which I think is part of the spirit of this repo. Unless I am missing something more fundamental that would inadvertently be putting the user in corner they can't get out of?  

Otherwise, for us, where linting plays a role in ensuring best practices for ourselves (and in theory for our users as a side effect) I see the value in keeping ourselves _more_ honest a higher imperative overall, given that anything that's unwanted can just as easily be deleted by the user.
