### ISSUE TITLE
improve Lighthouse SEO score for description (meta)

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood-getting-started#6]
Running a Lighthouse report, looks like we could improve the SEO score by adding a `<meta>` description.  
<img width="1137" alt="Screen Shot 2019-09-14 at 4 03 29 PM" src="https://user-images.githubusercontent.com/895923/64913206-1ac0d280-d70a-11e9-8120-33426438e849.png">

Wonder if this should be a Greenwood default instead?

**Comment by DevLab2425** [comment]
@thescientist13 
What are you thinking here? Simple update?

**Comment by thescientist13** [comment]
Couple options:
1. We could just add the description as its own [`meta`](https://www.greenwoodjs.io/docs/configuration#meta) configuration in [_greenwood.config.js_](https://github.com/thescientist13/greenwood-getting-started/blob/master/greenwood.config.js)
1. Or have Greenwood itself provide a default value for description by default, which would require an upstream issue / fix

Option 1 works for me for now, but would just be curious to get thoughts on #2 regarding the overall discussion of defaults in the project.  Only other consideration was just making sure the Getting Started stayed close to guide (i.e. not having too much extra that might make things harder to understand to a newbie).

I guess surprise me?  😄
