### ISSUE TITLE
Update the greenwood logo

### ISSUE THREAD

**Issue by jstockdi** [ProjectEvergreen/greenwood-getting-started#77]
Update 
  https://github.com/ProjectEvergreen/greenwood-getting-started/blob/master/src/assets/greenwood-logo.png
to
  https://github.com/ProjectEvergreen/greenwood/blob/master/www/assets/greenwood-logo-og.png

**Comment by thescientist13** [comment]
That would be great!  If you're up for making the contribution, maybe we could sneak in the #73 too 😅

**Comment by jstockdi** [comment]
See below for testing results.

<img width="565" alt="Screenshot 2023-11-05 at 7 34 11 AM" src="https://github.com/ProjectEvergreen/greenwood-getting-started/assets/1096460/9c00d994-9fdf-48fe-aca7-d0135072a64b">
