### ISSUE TITLE
Dependabot - Known Vulnerabilities

### ISSUE THREAD

**Issue by jstockdi** [ProjectEvergreen/greenwood-getting-started#80]
remote: GitHub found 4 vulnerabilities on ProjectEvergreen/greenwood-getting-started's default branch (2 critical, 1 high, 1 moderate). To find out more, visit:
remote:      https://github.com/ProjectEvergreen/greenwood-getting-started/security/dependabot

**Comment by thescientist13** [comment]
Looks like a couple of them are tracked in open dependabot PRs.  I think if I start merging them again, it should start picking them up again, so yeah, let me take a look.

I'm not sure how any of these manifest within _node_modules_ per se but if the builds passing, probably ain't hurting anything.

After I merge #76 I'll circle back on these.

**Comment by thescientist13** [comment]
Thanks, all caught up now!
